format = """
$os\
$username\
$hostname\
$c\
$lua\
$python\
$docker_context\
$package\
$container\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$directory\
$line_break\
$character"""


[os]
format = "[$symbol]($style)"
style = "bold white"
disabled = false

[os.symbols]
Macos = " "
Pop = " "
Raspbian = " "
Ubuntu = " "

[directory]
read_only = "󰌾"
truncation_length = 0
format = "in [$path]($style)[$read_only]($read_only_style) "

[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
ssh_symbol = ""
format = '@[$hostname](bold red)[$ssh_symbol](bold blue) '
trim_at = '.'
disabled = false

[python]
symbol = " "
format = 'writing [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rlang]
symbol = "󰟔 "

[c]
symbol = " "

[lua]
symbol = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[package]
symbol = "󰏗 "
format = 'packed with [$symbol$version]($style) '
